version: '3.8'

services:
  windows:
    image: docker.io/dockurr/windows
    container_name: windows11e
    environment:
      - VERSION=11e
      - DISK_SIZE=256g
      - RAM_SIZE=16G
      - CPU_CORES=12
      - REGION=no-NB
      - KEYBOARD=no-NB
      - USERNAME=bill
      - PASSWORD=gates
    ports:
      - 8006:8006
      - 8008:3389/tcp
      - 8008:3389/udp
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    volumes:
      - /mnt/d/dockur/windows11e:/storage
    stop_grace_period: 120s
    stdin_open: true
    tty: true
    restart: "no"
